name: Cloud Build

steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/jay67nie/library-mgt.git"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/library-system-386718/libdocker", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/library-system-386718/libdocker"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "libservice", "--image", "gcr.io/library-system-386718/libdocker", "--platform", "managed", "--region", "global"]
    env:
      - "SECRET_KEY=${_SECRET_KEY}"
      - "DATABASE_URL=${_DATABASE_URL}"

