name: Cloud Build

env:
  PROJECT_ID: library-system-386718
  IMAGE_NAME: dImage
  REGION: global
  SERVICE_NAME: myService
  DATABASE_URL: sqlite:///db.sqlite3
  SECRET_KEY: library1234
  DEBUG: "False"


steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/[GITHUB-USERNAME]/[REPO-NAME].git"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/[PROJECT-ID]/[IMAGE-NAME]", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/[PROJECT-ID]/[IMAGE-NAME]"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "[SERVICE-NAME]", "--image", "gcr.io/[PROJECT-ID]/[IMAGE-NAME]", "--platform", "managed", "--region", "[REGION]"]
    env:
      - "SECRET_KEY=${_SECRET_KEY}"
      - "DATABASE_URL=${_DATABASE_URL}"

