name: Cloud Build

on:
  push:
    branches:
      - test

env:
  PROJECT_ID: library-system-386718
  IMAGE_NAME: dImage
  REGION: global
  SERVICE_NAME: myService
  DATABASE_URL: sqlite:///db.sqlite3
  SECRET_KEY: library1234
  DEBUG: "False"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} .
          gcloud auth configure-docker
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

      - name: Deploy to Cloud Run
        uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@master
        with:
          service_name: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
          region: ${{ env.REGION }}
          platform: managed
          allow_unauthenticated: true
          env_vars: |
            DATABASE_URL=${{ env.DATABASE_URL }}
            SECRET_KEY=${{ env.SECRET_KEY }}
            DEBUG=${{ env.DEBUG }}
