# Generated by Django 4.0.5 on 2022-08-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_book',
            name='notified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
