# Generated by Django 4.0.5 on 2022-07-18 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('The_Library', '0002_borrowed_book_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_book',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
