# Generated by Django 4.0.5 on 2022-08-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Library', '0002_borrowed_book_due_date_alter_borrowed_book_student'),
        ('The_Library', '0003_alter_borrowed_book_student'),
    ]

    operations = [
    ]
