# Generated by Django 4.0.4 on 2022-08-20 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Library', '0003_alter_borrowed_book_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_book',
            name='borrow_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
